services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: electronicsdb
    
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    image: mnck/git_actions_docker_practice-backend:latest
    container_name: springboot
    build:
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - "1977:2099"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    image: mnck/git_actions_docker_practice-frontend:latest
    container_name: react
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: